### PR TITLE
Added all possible variants for DREQ

### PR DESCRIPTION
**Pull request by jounathaen**
I don't know why the svd only contains the timers here as triggers, but this is the full enum which can also be used in general in hals. This can e.g. replace/improve the [`dreq_value` function in the rp2040 hal](https://github.com/rp-rs/rp-hal/blob/9641c0b4a4b21ec9ffbce2a8cdbd90f629bc82ae/rp2040-hal/src/pio.rs#L1113)

### CODE REVIEW

**Review by 9names — APPROVED** [review]
Strange that the datasheet has most of these values in 2.5.3.1 table 119 and the timer ones in 2.5.7 table 124.
LGTM, thanks for the PR

**Comment by jounathaen** [comment]
I hope I rebased it correctly. Unfortunately `svdtools` fails at my machine with an `TypeError: Argument must be bytes or unicode, got 'int'`, but it also does so on the main branch. Guess "I'm holding it wrong".

**Comment by 9names** [comment]
Might be the wrong version of svdtools? Once we switch to the rust-based version that problem should be less common.
CI is happy, so I think you've done it right.

**Comment by jounathaen** [comment]
Alright, then I have nothing more to add here :slightly_smiling_face:

**Comment by jounathaen** [comment]
OK, I did have something more: A changelog entry. But now....

**Review by 9names — APPROVED** [review]

**Comment by jannic** [comment]
> Strange that the datasheet has most of these values in 2.5.3.1 table 119 and the timer ones in 2.5.7 table 124. LGTM, thanks for the PR

I guess the reason is that the timers are part of the DMA peripheral (which RP probably just imported from an existing IP block), and the DREQ ones are external, so different hardware designs could use different assignments.

That could also explain why the values are missing from the SVD: It may also be just copied in from some existing file for the DMA peripheral.

**Pull request merged**
