### PR TITLE
Arrayify spinlocks

### PR DESCRIPTION
**Pull request by 9names**
I've kept this as 3 separate commits to make it easier to review.
All 32 spinlock registers are the same, so make them an array to make them easier to access and make the PAC smaller.
The spinlock state register (SPINLOCK_ST) should be unmodified by this change.

### CODE REVIEW

**Comment by 9names** [comment]
Current svd2rust messes up the description field once the registers are arrayified.
I decided to just rewrite the description to make it more concise anyway, but I've written myself a todo to work out why svd2rust was mangling it.

The description is changed from
```
Reading from a spinlock address will:  
 - Return 0 if lock is already locked  
 - Otherwise return nonzero, and simultaneously claim the lock  
 Writing (any value) releases the lock.  
 If core 0 and core 1 attempt to claim the same lock simultaneously, core 0 wins.  
 The value returned on success is 0x1 << lock number. 
 ```
 to
 ```
Reading from a spinlock register will return zero if lock is already taken,
otherwise it will claim the lock and return (1u32 << lock number).
Writing any value to the register releases the lock.
If core zero and core one attempt to claim the same lock simultaneously, core zero wins.
 ```

**Comment by 9names** [comment]
I've rebased this on top of the current trunk.
The documentation changes have been dropped, fighting svd2rust is no fun and it's not worth it unless we can actually get it right.
I'll try to work out what needs to get added svd2rust to stop it substituting %s for 0, and make adding line breaks to strings possible.

**Comment by 9names** [comment]
Force push to remove an extra newline I accidentally added to rp2040.yaml, no other changes

**Review by jonathanpallant — DISMISSED** [review]
svdtools has done dumb things with the comments and replaced literal '0' with '%s' in a bunch of places, even converting `0x1` to `%sx1`.

**Comment by jonathanpallant** [comment]
I see there's a proposed patch to svdtools in https://github.com/stm32-rs/svdtools/pull/90

**Review by thejpster — APPROVED** [review]

**Comment by thejpster** [comment]
Woohoo! 🎉

**Pull request merged**
