### PR TITLE
Update crate version and changelog for release 0.4.0

### LINKED ISSUE #65: Publish latest changes
There have been some useful PRs since 0.3.0 release. In particular, I want access to the software interrupts. I'm using a local version of `rp2040_hal` to specify the latest pac from Github as dependency.

Can we bump the version to `0.3.1` and publish? I can work on a PR, but I don't know if there is a game plan.

Thanks!

### PR DESCRIPTION
**Pull request by 9names**
Please wait for #66 to land before merging this.
I think we should leave #61 until after release, we need to resolve how we're fixing the registers that are incorrectly labelled as clear on write. And also some objects now need parens for some reason.

Resolves #65

### CODE REVIEW

**Comment by jannic** [comment]
> Please wait for #66 to land before merging this.

#66 already contains all the commits from #67. Is that an accident?

**Comment by 9names** [comment]
That is indeed an accident

**Comment by 9names** [comment]
I've dropped the extra commit that should not have been there, hopefully I got it right this time

**Review by jannic — APPROVED** [review]
I wondered whether this should be 0.4.0 or 0.3.1.
However it looks like the new enum values added in https://github.com/rp-rs/rp2040-pac/commit/3182afffd319573237be8c6e2cea3a8cdf6e2eed are formally a breaking change, so going to 0.4.0 is the right choice. :+1:

**Pull request merged**
